[package]
name = "diesel_demo"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[dependencies]
diesel = { version = "1.4.6", features = ["mysql", "chrono"] }
dotenv = "0.15.0"
